name: searchlight_example
description: "Searchlight validation example app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cupertino_icons: ^1.0.8
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  path: ^1.9.1
  searchlight:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/search_corpus.json
    - assets/local/generated_search_corpus.json
    - assets/local/generated_search_snapshot.json
